version: '3.7'

services:
  web:
    build: ./app
    container_name: medusa_light_web
    restart: always
    command: bash entrypoint.sh
    volumes:
      - ./app:/usr/src/app
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    build: ./db
    container_name: medusa_light_db
    volumes:
      - medusa_light_library_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5432:5432

  nginx:
    build: ./nginx
    container_name: medusa_light_nginx
    restart: on-failure
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media
    depends_on:
      - web

volumes:
  medusa_light_library_postgres_data:
