# Generated by Django 4.0.1 on 2022-01-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiding', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={'ordering': ('-date',), 'verbose_name': 'Publication', 'verbose_name_plural': 'Publications'},
        ),
    ]
